services:
  gateway:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./microservicios/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - info_conciertos
    networks:
      - mi_red_privada
      - mi_red_publica

  info_conciertos:
    build:
      context: microservicios/infoconciertos
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ROOT_PATH=/info
    env_file:
      - microservicios/infoconciertos/ms.env
    networks:
      - mi_red_privada

  db:
    image: postgres:13
    env_file:
      - microservicios/db/midb.env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - mi_red_privada

volumes:
  db_data:
    driver: local

networks:
  mi_red_privada:
    internal: true
  mi_red_publica:
    driver: bridge

  
